name : ApartmentsPricePredictionWorkflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  end-to-end-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : test
        run: echo "Hello World"

      - name: test 2
        run: echo "Hello World"