name : ApartmentsPricePredictionWorkflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  end-to-end-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name : Configure dagshub dvc remote
        run: |
          dvc remote add origin https://dagshub.com/h49480749/apartments-price-prediction.dvc
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
      - name : Pull data from DVC remote
        run: |
          dvc pull -r origin
      - name : Run data preprocessing
        run: |
          python src/Data_Cleaning.py

      - name : Set MLflow environment variables
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name : Run model training
        run: |
          python src/Modelling.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push to ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/apartments-price-prediction:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Update AWS ECS
        run: |
          aws ecs update-service \
          --cluster apartments-prediction-cluster \ 
          --service apartments-prediction-service \
          --force-new-deployment \
          --region ${{ secrets.AWS_REGION }} 